name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: atlastixngdev.azurecr.io
        username: ${{ secrets.ACR_TOKEN }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: reg2.redhive.me/my-web-app:latest,reg2.redhive.me/my-web-app:${{ github.sha }},atlastixngdev.azurecr.io/atlastix/my-web-app:latest
