name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: reg2.redhive.me/my-web-app:latest
