name: workflow 1
run-name: ${{ github.actor }} test
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "what's your name"
        required: true
        type: choice
        options:
          - John
          - James
          - Paul
jobs:
  job1:
    runs-on: ubuntu-latest
    if: "inputs.name != ''"
    steps:
      - run: echo "hello ${{ inputs.name }}"
  job2:
    defaults:
      run:
        shell: python
    runs-on: ubuntu-latest
    if: "inputs.name != ''"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: |
          print("hello ${{ inputs.name }}")
