name: workflow 1
run-name: ${{ github.actor }} test
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by a ${{ github.event_name }} event."
      - name: checkout
        uses: actions/checkout@v4
