name: build and publish ui
run-name: publish to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        required: true
        type: environment

permissions:
  id-token: write
  contents: read


jobs:
  build:
    defaults:
      run:
        working-directory: ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: npm install

    - name: build assets
      run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        path: ui/build
        name: ui-build

  upload:
    needs:
      - build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_testing: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ui-build

    - run: tree
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --overwrite \
          --content-cache-control "public, max-age=31536000, immutable" \
          --account-name ${{ vars.UI_STORAGE_ACCOUNT }} \
          --auth-mode login \
          -d '$web' -s .
          az storage blob update \
          --content-cache-control "public, max-age=0, must-revalidate" \
          --account-name ${{ vars.UI_STORAGE_ACCOUNT }} \
          --auth-mode login \
          --container '$web' \
          --name index.html

    - name:
      env:
        ZZZZZZZZZZZZ: "testtest"
      run: |
        env | sort -n
  # Azure logout
    - name: logout
      run: |
        az logout
      if: always()
